import path from 'node:path'
import process from 'node:process'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vitest/config'

/**
 * `src/pages.json` 由 uni-pages 插件生成，里面带有 `// GENERATED BY ...` 注释，
 * 不是合法 JSON。构建时由 uni 自己的插件处理，但在 vitest 里会被 vite:json 直接解析报错。
 * 任何间接依赖 `@/utils`（它导入了 pages.json）的模块都会命中这个问题，所以在这里统一去掉注释。
 */
const stripPagesJsonComments = {
  name: 'strip-pages-json-comments',
  enforce: 'pre' as const,
  transform(code: string, id: string) {
    if (!id.replace(/\\/g, '/').endsWith('src/pages.json')) {
      return null
    }
    return { code: code.replace(/^\s*\/\/.*$/gm, ''), map: null }
  },
}

export default defineConfig({
  plugins: [stripPagesJsonComments, vue()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['src/test-setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'src/uni_modules/**'],
  },
  resolve: {
    alias: {
      '@': path.resolve(process.cwd(), 'src'),
      '@img': path.resolve(process.cwd(), 'src/static/images'),
    },
  },
})
